#!/bin/bash

echo "🚀 Audit Checklist Deployment Setup"
echo "=================================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. ✅ Code pushed to GitHub repository"
echo "2. 🔗 Railway account (https://railway.app)"
echo "3. 🌐 Vercel account (https://vercel.com)"
echo "4. 🔑 OpenAI API key"
echo ""

echo "📦 Backend Dependencies:"
echo "- psycopg2-binary (PostgreSQL adapter)"
echo "- gunicorn (WSGI server)"
echo "- whitenoise (Static files)"
echo "- dj-database-url (Database URL parser)"
echo ""

echo "🔧 Files Created/Updated:"
echo "- backend/requirements.txt (added PostgreSQL dependencies)"
echo "- backend/audit_project/settings.py (production-ready settings)"
echo "- backend/Procfile (Railway deployment)"
echo "- backend/runtime.txt (Python version)"
echo "- backend/env.example (environment variables template)"
echo "- backend/.gitignore (excludes sensitive files)"
echo "- frontend/vercel.json (Vercel configuration)"
echo "- DEPLOYMENT.md (comprehensive deployment guide)"
echo ""

echo "🎯 Next Steps:"
echo ""
echo "1. Push your code to GitHub:"
echo "   git add ."
echo "   git commit -m 'Add PostgreSQL and deployment configuration'"
echo "   git push origin main"
echo ""
echo "2. Deploy Backend to Railway:"
echo "   - Go to https://railway.app"
echo "   - Create new project from GitHub repo"
echo "   - Set root directory to 'backend'"
echo "   - Add PostgreSQL database"
echo "   - Configure environment variables"
echo ""
echo "3. Deploy Frontend to Vercel:"
echo "   - Go to https://vercel.com"
echo "   - Import GitHub repository"
echo "   - Set root directory to 'frontend'"
echo "   - Configure environment variables"
echo ""
echo "📖 See DEPLOYMENT.md for detailed instructions"
echo ""
echo "✨ Happy deploying!" 