# Generated by Django 4.2.7 on 2025-06-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='audit',
            name='description',
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(default='General Audit', max_length=100),
        ),
        migrations.AddField(
            model_name='audit',
            name='complexity_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='audit',
            name='industry',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='audit',
            name='organization',
            field=models.CharField(default='General Organization', max_length=200),
        ),
        migrations.AddField(
            model_name='audit',
            name='specific_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='item',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='order',
            field=models.IntegerField(),
        ),
    ]
